package com.tandemdiabetes.technicalinterview2.ui

import androidx.compose.runtime.Composable
import com.tandemdiabetes.technicalinterview2.Emoji

@Composable
fun EmojisScreen() {
    // 1) TODO implement the screen to display a list of emojis and the ablity to sort them ascending or descending
    // 2) TODO add a search bar to filter the list of emojis

}

private val emojiList = listOf(
    Emoji("Grinning Face", "😀"),
    Emoji("Grinning Face with Big Eyes", "😃"),
    Emoji("Grinning Face with Smiling Eyes", "😄"),
    Emoji("Beaming Face with Smiling Eyes", "😁"),
    Emoji("Grinning Squinting Face", "😆"),
    Emoji("Grinning Face with Sweat", "😅"),
    Emoji("Rolling on the Floor Laughing", "🤣"),
    Emoji("Face with Tears of Joy", "😂"),
    Emoji("Slightly Smiling Face", "🙂"),
    Emoji("Upside-Down Face", "🙃"),
    Emoji("Winking Face", "😉"),
    Emoji("Smiling Face with Smiling Eyes", "😊"),
    Emoji("Smiling Face with Halo", "😇"),
    Emoji("Smiling Face with Hearts", "🥰"),
    Emoji("Smiling Face with Heart-Eyes", "😍"),
    Emoji("Star-Struck", "🤩"),
    Emoji("Face Blowing a Kiss", "😘"),
    Emoji("Kissing Face", "😗"),
    Emoji("Smiling Face", "☺️"),
    Emoji("Kissing Face with Closed Eyes", "😚"),
    Emoji("Kissing Face with Smiling Eyes", "😙"),
    Emoji("Smiling Face with Tear", "🥲"),
    Emoji("Face Savoring Food", "😋"),
    Emoji("Face with Tongue", "😛"),
    Emoji("Winking Face with Tongue", "😜"),
    Emoji("Zany Face", "🤪"),
    Emoji("Squinting Face with Tongue", "😝"),
    Emoji("Money-Mouth Face", "🤑"),
    Emoji("Hugging Face", "🤗"),
    Emoji("Face with Hand Over Mouth", "🤭"),
    Emoji("Shushing Face", "🤫"),
    Emoji("Thinking Face", "🤔"),
    Emoji("Zipper-Mouth Face", "🤐"),
    Emoji("Face with Raised Eyebrow", "🤨"),
    Emoji("Neutral Face", "😐"),
    Emoji("Expressionless Face", "😑"),
    Emoji("Face Without Mouth", "😶"),
    Emoji("Smirking Face", "😏"),
    Emoji("Unamused Face", "😒"),
    Emoji("Face with Rolling Eyes", "🙄"),
    Emoji("Grimacing Face", "😬"),
    Emoji("Lying Face", "🤥"),
    Emoji("Relieved Face", "😌"),
    Emoji("Pensive Face", "😔"),
    Emoji("Sleepy Face", "😪"),
    Emoji("Drooling Face", "🤤"),
    Emoji("Sleeping Face", "😴"),
    Emoji("Face with Medical Mask", "😷"),
    Emoji("Face with Thermometer", "🤒"),
    Emoji("Face with Head-Bandage", "🤕"),
    Emoji("Nauseated Face", "🤢"),
    Emoji("Sneezing Face", "🤧"),
    Emoji("Face Vomiting", "🤮"),
    Emoji("Hot Face", "🥵"),
    Emoji("Cold Face", "🥶"),
    Emoji("Woozy Face", "🥴"),
    Emoji("Dizzy Face", "😵"),
    Emoji("Exploding Head", "🤯"),
    Emoji("Cowboy Hat Face", "🤠"),
    Emoji("Partying Face", "🥳"),
    Emoji("Disguised Face", "🥸"),
    Emoji("Smiling Face with Sunglasses", "😎"),
    Emoji("Nerd Face", "🤓"),
    Emoji("Face with Monocle", "🧐"),
    Emoji("Confused Face", "😕"),
    Emoji("Worried Face", "😟"),
    Emoji("Slightly Frowning Face", "🙁"),
    Emoji("Frowning Face", "☹️"),
    Emoji("Face with Open Mouth", "😮"),
    Emoji("Hushed Face", "😯"),
    Emoji("Astonished Face", "😲"),
    Emoji("Flushed Face", "😳"),
    Emoji("Pleading Face", "🥺"),
    Emoji("Frowning Face with Open Mouth", "😦"),
    Emoji("Anguished Face", "😧"),
    Emoji("Fearful Face", "😨"),
    Emoji("Anxious Face with Sweat", "😰"),
    Emoji("Sad but Relieved Face", "😥"),
    Emoji("Crying Face", "😢"),
    Emoji("Loudly Crying Face", "😭"),
    Emoji("Face Screaming in Fear", "😱"),
    Emoji("Confounded Face", "😖"),
    Emoji("Persevering Face", "😣"),
    Emoji("Disappointed Face", "😞"),
    Emoji("Downcast Face with Sweat", "😓"),
    Emoji("Weary Face", "😩"),
    Emoji("Tired Face", "😫"),
    Emoji("Yawning Face", "🥱"),
    Emoji("Face with Steam From Nose", "😤"),
    Emoji("Pouting Face", "😡"),
    Emoji("Angry Face", "😠"),
    Emoji("Face with Symbols on Mouth", "🤬"),
    Emoji("Smiling Face with Horns", "😈"),
    Emoji("Angry Face with Horns", "👿"),
    Emoji("Skull", "💀"),
    Emoji("Skull and Crossbones", "☠️"),
    Emoji("Pile of Poo", "💩"),
    Emoji("Clown Face", "🤡"),
    Emoji("Ogre", "👹"),
)
